import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { jsPDF } from 'npm:jspdf@2.5.1';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'npm:docx@8.5.0';

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();

        if (!user) {
            return Response.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { 
            start_date, 
            end_date, 
            topics, 
            persona, 
            format, 
            custom_instructions,
            language = 'pt'
        } = await req.json();

        // Buscar dados relevantes do período
        const [publications, strategicFacts, geopoliticalRisks] = await Promise.all([
            base44.entities.Publication.filter({
                publication_date: { $gte: start_date, $lte: end_date }
            }),
            base44.entities.StrategicFact.filter({
                start_date: { $gte: start_date, $lte: end_date }
            }),
            base44.entities.GeopoliticalRisk.filter({
                created_date: { $gte: start_date, $lte: end_date }
            })
        ]);

        // Definir estilo de persona
        const personaStyles = {
            executivo: language === 'pt' 
                ? 'Estilo executivo: conciso, estratégico, foco em insights acionáveis e recomendações práticas. Use bullet points e highlights.'
                : 'Executive style: concise, strategic, focus on actionable insights and practical recommendations. Use bullet points and highlights.',
            academico: language === 'pt'
                ? 'Estilo acadêmico: profundo, referenciado, análise teórica robusta com citações completas e metodologia clara.'
                : 'Academic style: deep, referenced, robust theoretical analysis with complete citations and clear methodology.',
            diplomatico: language === 'pt'
                ? 'Estilo diplomático: nuançado, equilibrado, apresenta múltiplas perspectivas com linguagem formal e respeitosa.'
                : 'Diplomatic style: nuanced, balanced, presents multiple perspectives with formal and respectful language.',
            jornalistico: language === 'pt'
                ? 'Estilo jornalístico: claro, factual, narrativo, acessível ao público geral com linguagem objetiva.'
                : 'Journalistic style: clear, factual, narrative, accessible to general public with objective language.'
        };

        // Gerar conteúdo com LLM
        const reportPrompt = `
Você é Marcos Prado Troyjo. Gere um relatório estratégico personalizado com as seguintes especificações:

**Período**: ${start_date} a ${end_date}
**Tópicos**: ${topics.join(', ')}
**Estilo**: ${personaStyles[persona] || personaStyles.executivo}
**Instruções adicionais**: ${custom_instructions || 'Nenhuma'}

**Dados disponíveis no período**:
- ${publications.length} publicações
- ${strategicFacts.length} fatos estratégicos
- ${geopoliticalRisks.length} riscos geopolíticos identificados

**Estrutura do relatório**:

1. **Sumário Executivo** (máximo 200 palavras)
   - Principais conclusões e insights

2. **Contexto Geopolítico** 
   - Análise do cenário no período
   - Eventos-chave que impactaram os tópicos selecionados

3. **Análise por Tópico**
   Para cada tópico em ${topics.join(', ')}:
   - Principais desenvolvimentos
   - Tendências observadas
   - Riscos e oportunidades
   - Dados e métricas relevantes

4. **Insights e Perspectivas Troyjo**
   - Aplicação de frameworks conceituais (desglobalização, trumpulência, Novo ESG, etc)
   - Leitura geoeconomica única
   - Implicações para competitividade

5. **Recomendações Estratégicas**
   - Ações sugeridas baseadas na análise
   - Pontos de atenção

6. **Fontes e Referências**
   - Liste todas as fontes utilizadas

Use markdown para formatação. Seja rigoroso com dados e cite fontes específicas quando disponíveis.
`;

        const llmResponse = await base44.integrations.Core.InvokeLLM({
            prompt: reportPrompt,
            add_context_from_internet: true
        });

        const reportContent = llmResponse;
        const reportTitle = language === 'pt' 
            ? `Relatório Estratégico - ${topics[0]} - ${start_date} a ${end_date}`
            : `Strategic Report - ${topics[0]} - ${start_date} to ${end_date}`;

        // Gerar arquivo
        if (format === 'pdf') {
            const doc = new jsPDF();
            let y = 20;

            // Title
            doc.setFontSize(18);
            doc.setFont(undefined, 'bold');
            doc.text(reportTitle, 20, y);
            y += 10;

            doc.setFontSize(10);
            doc.setFont(undefined, 'normal');
            doc.text(`${language === 'pt' ? 'Gerado por' : 'Generated by'}: Marcos Troyjo Digital Twin`, 20, y);
            y += 5;
            doc.text(`${language === 'pt' ? 'Data' : 'Date'}: ${new Date().toLocaleDateString()}`, 20, y);
            y += 10;

            // Content
            doc.setFontSize(11);
            const lines = doc.splitTextToSize(reportContent, 170);
            lines.forEach((line) => {
                if (y > 280) {
                    doc.addPage();
                    y = 20;
                }
                doc.text(line, 20, y);
                y += 6;
            });

            const pdfBytes = doc.output('arraybuffer');
            return new Response(pdfBytes, {
                headers: {
                    'Content-Type': 'application/pdf',
                    'Content-Disposition': `attachment; filename=report_${start_date}_${end_date}.pdf`
                }
            });
        } else {
            // Generate DOCX
            const paragraphs = reportContent.split('\n\n').map(text => 
                new Paragraph({
                    children: [new TextRun(text)],
                    spacing: { after: 200 }
                })
            );

            const doc = new Document({
                sections: [{
                    properties: {},
                    children: [
                        new Paragraph({
                            text: reportTitle,
                            heading: HeadingLevel.HEADING_1,
                            alignment: AlignmentType.CENTER,
                            spacing: { after: 400 }
                        }),
                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: `${language === 'pt' ? 'Gerado por' : 'Generated by'}: Marcos Troyjo Digital Twin`,
                                    italics: true,
                                    size: 20
                                })
                            ],
                            spacing: { after: 200 }
                        }),
                        ...paragraphs
                    ]
                }]
            });

            const buffer = await Packer.toBuffer(doc);
            return new Response(buffer, {
                headers: {
                    'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    'Content-Disposition': `attachment; filename=report_${start_date}_${end_date}.docx`
                }
            });
        }
    } catch (error) {
        console.error('Error generating custom report:', error);
        return Response.json({ error: error.message }, { status: 500 });
    }
});