import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Info, ChevronDown, ChevronUp, Brain, TrendingUp, AlertCircle } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';

export default function XAIExplainer({ 
    prediction, 
    explanation,
    featureImportance = [],
    lang = 'pt' 
}) {
    const [expanded, setExpanded] = useState(false);

    const t = {
        pt: {
            why: 'Por que esta previsão?',
            confidence: 'Confiança',
            keyFactors: 'Fatores-Chave',
            dataPoints: 'Pontos de Dados',
            methodology: 'Metodologia',
            learnMore: 'Saiba Mais',
            showLess: 'Mostrar Menos',
            basedOn: 'Baseado em',
            influence: 'Influência'
        },
        en: {
            why: 'Why this prediction?',
            confidence: 'Confidence',
            keyFactors: 'Key Factors',
            dataPoints: 'Data Points',
            methodology: 'Methodology',
            learnMore: 'Learn More',
            showLess: 'Show Less',
            basedOn: 'Based on',
            influence: 'Influence'
        }
    }[lang];

    return (
        <Card className="border-l-4 border-l-indigo-500 bg-gradient-to-br from-indigo-50/50 to-purple-50/50 dark:from-indigo-900/20 dark:to-purple-900/20">
            <CardHeader className="pb-3">
                <div className="flex items-start justify-between">
                    <div className="flex items-center gap-2">
                        <Brain className="w-5 h-5 text-indigo-600" />
                        <CardTitle className="text-sm font-semibold text-gray-900 dark:text-white">
                            {t.why}
                        </CardTitle>
                    </div>
                    <TooltipProvider>
                        <Tooltip>
                            <TooltipTrigger>
                                <Info className="w-4 h-4 text-gray-400" />
                            </TooltipTrigger>
                            <TooltipContent>
                                <p className="text-xs">
                                    {lang === 'pt' 
                                        ? 'Explicação gerada por IA Explicável (XAI)'
                                        : 'Explanation generated by Explainable AI (XAI)'}
                                </p>
                            </TooltipContent>
                        </Tooltip>
                    </TooltipProvider>
                </div>
            </CardHeader>
            <CardContent className="space-y-4">
                {/* Confidence Score */}
                <div>
                    <div className="flex items-center justify-between mb-2">
                        <span className="text-xs font-medium text-gray-600 dark:text-gray-400">
                            {t.confidence}
                        </span>
                        <span className="text-xs font-bold text-indigo-600">
                            {((prediction?.confidence_score || 0.5) * 100).toFixed(0)}%
                        </span>
                    </div>
                    <Progress 
                        value={(prediction?.confidence_score || 0.5) * 100} 
                        className="h-2"
                    />
                </div>

                {/* Main Explanation */}
                <div className="p-3 bg-white dark:bg-gray-800 rounded-lg text-sm text-gray-700 dark:text-gray-300">
                    {explanation || prediction?.reasoning}
                </div>

                {/* Feature Importance */}
                {featureImportance.length > 0 && (
                    <div>
                        <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-2">
                            {t.keyFactors}:
                        </p>
                        <div className="space-y-2">
                            {featureImportance.slice(0, expanded ? undefined : 3).map((feature, idx) => (
                                <motion.div
                                    key={idx}
                                    initial={{ opacity: 0, x: -10 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: idx * 0.05 }}
                                    className="flex items-center gap-2"
                                >
                                    <div className="flex-1">
                                        <div className="flex items-center justify-between mb-1">
                                            <span className="text-xs text-gray-600 dark:text-gray-400">
                                                {feature.name || feature}
                                            </span>
                                            <span className="text-xs font-medium text-indigo-600">
                                                {((feature.importance || 0.5) * 100).toFixed(0)}%
                                            </span>
                                        </div>
                                        <Progress 
                                            value={(feature.importance || 0.5) * 100} 
                                            className="h-1.5"
                                        />
                                    </div>
                                </motion.div>
                            ))}
                        </div>
                    </div>
                )}

                {/* Expand/Collapse */}
                {(featureImportance.length > 3 || explanation) && (
                    <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => setExpanded(!expanded)}
                        className="w-full gap-2 text-indigo-600"
                    >
                        {expanded ? (
                            <>
                                {t.showLess}
                                <ChevronUp className="w-4 h-4" />
                            </>
                        ) : (
                            <>
                                {t.learnMore}
                                <ChevronDown className="w-4 h-4" />
                            </>
                        )}
                    </Button>
                )}

                <AnimatePresence>
                    {expanded && (
                        <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: 'auto' }}
                            exit={{ opacity: 0, height: 0 }}
                            className="space-y-3 pt-3 border-t border-gray-200 dark:border-gray-700"
                        >
                            {/* Data Sources */}
                            {prediction?.based_on && (
                                <div>
                                    <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-2">
                                        {t.basedOn}:
                                    </p>
                                    <div className="grid grid-cols-2 gap-2 text-xs">
                                        {Object.entries(prediction.based_on).map(([key, value]) => (
                                            <div key={key} className="flex items-center justify-between p-2 bg-white dark:bg-gray-800 rounded">
                                                <span className="text-gray-600 dark:text-gray-400 capitalize">
                                                    {key.replace(/_/g, ' ')}
                                                </span>
                                                <span className="font-medium text-gray-900 dark:text-white">
                                                    {typeof value === 'number' ? value : Array.isArray(value) ? value.length : '-'}
                                                </span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {/* Methodology */}
                            <div className="p-3 bg-indigo-50 dark:bg-indigo-900/20 rounded-lg">
                                <p className="text-xs font-semibold text-indigo-900 dark:text-indigo-300 mb-1">
                                    {t.methodology}:
                                </p>
                                <p className="text-xs text-indigo-700 dark:text-indigo-400">
                                    {lang === 'pt'
                                        ? 'Análise baseada em GPT-4 com processamento de dados históricos, padrões geopolíticos e indicadores econômicos.'
                                        : 'GPT-4 based analysis with historical data processing, geopolitical patterns and economic indicators.'}
                                </p>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </CardContent>
        </Card>
    );
}